import { NextResponse } from "next/server"
import { put } from "@vercel/blob"

const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB

const ALLOWED_FILE_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/png",
]

const ALLOWED_DOCUMENT_TYPES = [
  "idFront",
  "idBack",
  "bankStatement",
  "proofOfAddress",
  "payslips",
] as const

type DocumentType =
  (typeof ALLOWED_DOCUMENT_TYPES)[number]

export async function POST(request: Request) {
  try {
    const formData = await request.formData()

    const file = formData.get("file")
    const applicationId = formData.get("applicationId")
    const documentType = formData.get("documentType")

    // ---------------------------------------------------------
    // 1. Validate file
    // ---------------------------------------------------------

    if (!(file instanceof File) || file.size === 0) {
      return NextResponse.json(
        {
          success: false,
          message: "No file was provided.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 2. Validate application ID
    // ---------------------------------------------------------

    if (
      typeof applicationId !== "string" ||
      !applicationId.trim()
    ) {
      return NextResponse.json(
        {
          success: false,
          message: "Application ID is required.",
        },
        { status: 400 }
      )
    }

    const cleanApplicationId =
      applicationId.trim()

    // Application IDs generated by submitApplication()
    // follow the format:
    // OPT-1234567890-ABCDE

    if (
      !/^OPT-\d{10,}-[A-Z0-9]{5}$/.test(
        cleanApplicationId
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          message: "Invalid application ID.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 3. Validate document type
    // ---------------------------------------------------------

    if (
      typeof documentType !== "string" ||
      !documentType.trim()
    ) {
      return NextResponse.json(
        {
          success: false,
          message: "Document type is required.",
        },
        { status: 400 }
      )
    }

    if (
      !ALLOWED_DOCUMENT_TYPES.includes(
        documentType as DocumentType
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          message: "Invalid document type.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 4. Validate file type
    // ---------------------------------------------------------

    if (!ALLOWED_FILE_TYPES.includes(file.type)) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Only PDF, JPG, JPEG and PNG files are allowed.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 5. Validate file size
    // ---------------------------------------------------------

    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json(
        {
          success: false,
          message:
            "File is too large. Maximum size is 10MB.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 6. Validate file extension
    // ---------------------------------------------------------

    const extension =
      file.name
        .split(".")
        .pop()
        ?.toLowerCase()

    const allowedExtensions = [
      "pdf",
      "jpg",
      "jpeg",
      "png",
    ]

    if (
      !extension ||
      !allowedExtensions.includes(extension)
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Invalid file extension. Only PDF, JPG, JPEG and PNG files are allowed.",
        },
        { status: 400 }
      )
    }

    // ---------------------------------------------------------
    // 7. Create controlled filename
    // ---------------------------------------------------------

    const filename =
      `applications/${cleanApplicationId}/${documentType}-${Date.now()}.${extension}`

    // ---------------------------------------------------------
    // 8. Upload to Vercel Blob
    // ---------------------------------------------------------

    const blob = await put(
      filename,
      file,
      {
        access: "public",
        addRandomSuffix: false,
      }
    )

    // ---------------------------------------------------------
    // 9. Return upload result
    // ---------------------------------------------------------

    return NextResponse.json({
      success: true,
      url: blob.url,
      pathname: blob.pathname,
    })
  } catch (error) {
    console.error(
      "Document upload error:",
      error
    )

    return NextResponse.json(
      {
        success: false,
        message:
          "Failed to upload document. Please try again.",
      },
      { status: 500 }
    )
  }
}
